apiVersion: apps/v1
kind: Deployment
metadata:
  name: jerney-backend
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jerney-backend
  template:
    metadata:
      labels:
        app: jerney-backend
    spec:
      containers:
        - name: jerney-backend
          image: imbivek01/blog-backend:5667d925
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 5000
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 5000
          #   initialDelaySeconds: 15
          #   periodSeconds: 10